services:

  php:
    build:
      context: ./frankenphp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./src/:/app/public
      - ./.caddy_data:/data
      - ./.caddy_config:/config
      - ./frankenphp/caddy/etc/Caddyfile:/etc/caddy/Caddyfile
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    networks:
      - magento

  rabbitmq:
    image: arm64v8/rabbitmq:3.11-management
    container_name: ${PROJECT_NAME}-rabbitmq
    environment:
      - VIRTUAL_HOST=rabbit.${PROJECT_VIRTUAL_HOST}
      - VIRTUAL_PORT=15672
    env_file:
      - ./rabbitmq/conf/rabbitmq.env
    volumes:
      - ./rabbitmq/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    expose:
      - 15672
    networks:
      - magento

  redis:
    image: arm64v8/redis:7.0
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "6379:6379"
    networks:
      - magento

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: ${PROJECT_NAME}-opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: always
    networks:
      - magento
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "http.host=0.0.0.0"
      - "DISABLE_SECURITY_PLUGIN=true"
      - VIRTUAL_HOST=search.${PROJECT_VIRTUAL_HOST}
      - VIRTUAL_PORT=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: ${PROJECT_NAME}-opensearch-dashboard
    restart: always
    networks:
      - magento
    environment:
      - VIRTUAL_HOST=dashboard.${PROJECT_VIRTUAL_HOST}
      - VIRTUAL_PORT=5601
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
    volumes:
      - ./opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - "5601:5601"
    expose:
      - "5601"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536

  mysql:
    image: arm64v8/mysql:8.0.34
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: 'magento'
      MYSQL_ROOT_PASSWORD: 'root_pass'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - "3308:3306"
    networks:
      - magento

  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME}-mailhog
    environment:
      - VIRTUAL_HOST=mail.${PROJECT_VIRTUAL_HOST}
      - VIRTUAL_PORT=8025
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento
    expose:
      - 8025

networks:
  magento:
    driver: bridge